# Generated by Django 3.2.9 on 2021-11-05 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commented', models.DateTimeField(auto_now_add=True)),
                ('user_commented', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('image', models.BinaryField(blank=True)),
                ('title', models.TextField()),
                ('short_description', models.TextField()),
                ('detail_description', models.TextField()),
                ('no_of_comments', models.PositiveSmallIntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user_posted', models.TextField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='food_critics.comments')),
            ],
        ),
    ]
