# Generated by Django 3.2.9 on 2021-11-05 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_critics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodblog',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='food_critics.foodblog'),
            preserve_default=False,
        ),
    ]
