# Generated by Django 3.2.9 on 2021-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_critics', '0002_auto_20211105_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodblog',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
