# Generated by Django 3.2.9 on 2021-11-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_critics', '0003_alter_foodblog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
