# Generated by Django 3.2.9 on 2021-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_critics', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='user'),
            preserve_default=False,
        ),
    ]
