# Generated by Django 3.2.9 on 2021-11-17 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_critics', '0006_blogger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogger',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
